'use client';

import { motion } from 'framer-motion';
import { useState } from 'react';
import SectionHeader from './SectionHeader';
import AudioPlayer from './AudioPlayer';
import TraceExplorer from './TraceExplorer';
import { STAGED_TRACE } from '@/lib/trace-data';

// the morning-test ritual that was actually generated by v2 in experiments/04.
// audio src is /staged-demo.mp3 which is a copy of experiments/04/final_audio.mp3.

const SCRIPT_BEATS: string[] = STAGED_TRACE.final_script.split('\n');
// approx total duration in seconds (v2 mp3 with prosody breaks is ~66s)
const TOTAL_SECONDS = 66;

const INPUTS: Array<[string, string]> = [
  ['mode', STAGED_TRACE.inputs.mode],
  ['intent', STAGED_TRACE.inputs.intent],
  ['first action', STAGED_TRACE.inputs.first_action],
  ['hero', STAGED_TRACE.inputs.hero],
  ['phrase', STAGED_TRACE.inputs.phrase],
  ['variant', STAGED_TRACE.inputs.variant],
  ['voice', `${STAGED_TRACE.inputs.voice} (harvey specter energy — calm, authoritative)`],
];

export default function StagedDemo() {
  const [activeBeat, setActiveBeat] = useState<number>(-1);
  const handleTime = (current: number) => {
    if (!current || !TOTAL_SECONDS) return setActiveBeat(-1);
    const nonEmpty = SCRIPT_BEATS.map((b, i) => ({ b, i })).filter((x) => x.b.trim().length > 0);
    const idx = Math.min(nonEmpty.length - 1, Math.floor((current / TOTAL_SECONDS) * nonEmpty.length));
    setActiveBeat(nonEmpty[idx]?.i ?? -1);
  };

  return (
    <section id="staged-demo" className="relative w-full py-24 md:py-32">
      <div className="mx-auto w-full max-w-6xl px-6 md:px-12">
        <SectionHeader
          caption="01 — the morning test"
          headline="the ritual that played on me at 6am tuesday"
          body={
            <>
              i set my alarm for 6am with one commitment: ship the OATH v1 spec to github before noon. this is what
              the v2 engine produced for that exact intent, voiced by &quot;the_closer&quot; (calm, authoritative —
              harvey specter energy).
            </>
          }
        />

        <div className="mt-14 grid md:grid-cols-[1fr_1fr] gap-6 md:gap-10">
          {/* inputs panel */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-80px' }}
            transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
            className="rounded-2xl border border-fg-dim/60 bg-bg-raised p-6 md:p-8"
          >
            <div className="caption mb-5 text-amber-dim">the inputs</div>
            <div className="space-y-3">
              {INPUTS.map(([k, v]) => (
                <div key={k} className="grid grid-cols-[110px_1fr] gap-4 items-start py-2 border-b border-fg-dim/40 last:border-0">
                  <div className="font-mono text-[0.75rem] uppercase tracking-[0.08em] text-fg-subtle pt-0.5">
                    {k}
                  </div>
                  <div className="text-[0.9375rem] text-fg leading-snug">{v}</div>
                </div>
              ))}
            </div>
          </motion.div>

          {/* audio player */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-80px' }}
            transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1], delay: 0.1 }}
            className="rounded-2xl border border-fg-dim/60 bg-bg-raised p-6 md:p-8 flex flex-col"
          >
            <div className="caption mb-5 text-amber-dim">the ritual</div>
            <div className="flex-1 flex flex-col justify-center">
              <AudioPlayer
                src="/staged-demo.mp3"
                downloadName="oath-morning-test.mp3"
                size="lg"
                onTimeUpdate={handleTime}
              />
            </div>
            <div className="mt-5 text-[0.75rem] font-mono text-fg-subtle tracking-wide">
              v2 engine · hardest_work · 141 words · {STAGED_TRACE.prosody_break_count} {'<break />'} tags · ~66s · judge {STAGED_TRACE.final_judge_score}/10
            </div>
          </motion.div>
        </div>

        {/* trace explorer — THE proof artifact */}
        <motion.div
          initial={{ opacity: 0, y: 18 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-80px' }}
          transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1], delay: 0.15 }}
          className="mt-8"
        >
          <TraceExplorer />
        </motion.div>

        {/* script as karaoke */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-100px' }}
          transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1], delay: 0.2 }}
          className="mt-12 md:mt-16 rounded-2xl border border-fg-dim/40 bg-bg-raised/40 p-8 md:p-12"
        >
          <div className="caption mb-6 text-amber-dim">the script — karaoke highlights as audio plays</div>
          <div className="font-sans text-[1.125rem] md:text-[1.25rem] leading-[1.85] max-w-3xl">
            {SCRIPT_BEATS.map((line, i) => {
              if (line === '') return <div key={i} className="h-3" />;
              const active = i === activeBeat;
              return (
                <p
                  key={i}
                  className={`transition-colors duration-200 ${active ? 'text-amber' : 'text-fg'}`}
                >
                  {line}
                </p>
              );
            })}
          </div>
        </motion.div>
      </div>
    </section>
  );
}
