import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OATH — the anti-feed morning ritual",
  description:
    "you swear tomorrow's hardest task at night. the alarm fires. one ritual plays. no scrolling. one button to start.",
  openGraph: {
    title: "OATH — the anti-feed morning ritual",
    description:
      "personalized 45-90 second audio ritual at alarm dismiss. generated by claude sonnet 4.6 + elevenlabs flash v2.5.",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "OATH — the anti-feed morning ritual",
    description:
      "personalized 45-90 second audio ritual at alarm dismiss. generated by claude sonnet 4.6 + elevenlabs flash v2.5.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-bg text-fg">{children}</body>
    </html>
  );
}
